input:
  imap:
    server: imap.example.com
    # port: 993
    username: user@example.com
    password: ''
    # folder: ''
    # filter: ''
    # post_action:
    #   flag: SEEN

# conversion:
#   wkhtmltopdf:
#     options: ''

output:
  smtp:
    server: smtp.example.com
    #port: 587
    # username: user@example.com
    # password: ''
    #encryption: STARTTLS
    sender: user@example.com
    destination: user@example.com
  # folder:
    # destination: ../output

# logging:
#   level: INFO
#   output_msg_on_error: false

